export const defaultMapStyle = {
  version: 8,
  sources: {
    stamen_toner: {
      type: "raster",
      tiles: ["https://stamen-tiles.a.ssl.fastly.net/toner/{z}/{x}/{y}.png"],
      tileSize: 256,
      attribution:
        'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.',
    },
    poi_geojson: {
      type: "geojson",
      data: null,
    },
    company_geojson: {
      type: "geojson",
      data: null,
    },
    selected_geojson: {
      type: "geojson",
      data: null,
    },
  },
  sprite: "",
  glyphs: "https://yuchuntsao.github.io/fonts/{fontstack}/{range}.pbf",
  layers: [
    {
      id: "background",
      type: "background",
      minzoom: 0,
      paint: {
        "background-color": "rgba(255, 255, 255, 1)",
      },
    },
    {
      id: "stamen_toner",
      type: "raster",
      source: "stamen_toner",
      paint: {
        "raster-opacity": [
          "interpolate",
          ["exponential", 0.5],
          ["zoom"],
          9,
          0.3,
          18,
          0.4,
        ],
      },
    },
    {
      id: "3C",
      source: "poi_geojson",
      type: "symbol",
      layout: {
        "text-anchor": "top",
        "text-field": "{name}",
        "text-font": ["Noto Sans Regular"],
        "text-offset": [0, 0.8],
        "text-padding": 2,
        "text-size": 14,
        "icon-image": "{subclass}",
        "text-max-width": 30,
      },
      paint: {
        "text-color": [
          "case",
          ["boolean", ["feature-state", "hover"], false],
          "rgba(3, 117, 214, 1)",
          "#133B8F",
        ],
        "text-halo-color": "#ffffff",
        "text-halo-width": 1,
      },
      filter: ["all", ["==", "status", "Active"], ["==", "class", "3C"]],
    },
    {
      id: "電信",
      source: "poi_geojson",
      type: "symbol",
      layout: {
        "text-anchor": "top",
        "text-field": "{name}",
        "text-font": ["Noto Sans Regular"],
        "text-offset": [0, 0.8],
        "text-padding": 2,
        "text-size": 14,
        "icon-image": "{subclass}",
        "text-max-width": 30,
      },
      paint: {
        "text-color": [
          "case",
          ["boolean", ["feature-state", "hover"], false],
          "rgba(3, 117, 214, 1)",
          "#133B8F",
        ],
        "text-halo-color": "#ffffff",
        "text-halo-width": 1,
      },
      filter: ["all", ["==", "status", "Active"], ["==", "class", "電信"]],
    },
    {
      id: "transportation",
      source: "poi_geojson",
      type: "symbol",
      layout: {
        "text-anchor": "top",
        "text-field": "{name}",
        "text-font": ["Noto Sans Regular"],
        "text-offset": [0, 0.8],
        "text-padding": 2,
        "text-size": 14,
        "icon-image": "{subclass}",
        "text-max-width": 30,
      },
      paint: {
        "text-color": [
          "case",
          ["boolean", ["feature-state", "hover"], false],
          "rgba(3, 117, 214, 1)",
          "#00609A",
        ],
        "text-halo-color": "#ffffff",
        "text-halo-width": 1,
      },
      filter: ["all", ["==", "status", "Active"], ["==", "class", "交通"]],
    },
    {
      id: "shop",
      source: "poi_geojson",
      type: "symbol",
      layout: {
        "text-anchor": "top",
        "text-field": "{name}",
        "text-font": ["Noto Sans Regular"],
        "text-offset": [0, 0.8],
        "text-padding": 2,
        "text-size": 14,
        "icon-image": "{subclass}",
        "text-max-width": 30,
      },
      paint: {
        "text-color": [
          "case",
          ["boolean", ["feature-state", "hover"], false],
          "rgba(3, 117, 214, 1)",
          "#BD1D6D",
        ],
        "text-halo-color": "#ffffff",
        "text-halo-width": 1,
      },
      filter: ["all", ["==", "status", "Active"], ["==", "class", "商店"]],
    },
    {
      id: "home",
      source: "poi_geojson",
      type: "symbol",
      layout: {
        "text-anchor": "top",
        "text-field": "{name}",
        "text-font": ["Noto Sans Regular"],
        "text-offset": [0, 0.8],
        "text-padding": 2,
        "text-size": 14,
        "icon-image": "{subclass}",
        "text-max-width": 30,
      },
      paint: {
        "text-color": [
          "case",
          ["boolean", ["feature-state", "hover"], false],
          "rgba(3, 117, 214, 1)",
          "#027502",
        ],
        "text-halo-color": "#ffffff",
        "text-halo-width": 1,
      },
      filter: ["all", ["==", "status", "Active"], ["==", "class", "居家"]],
    },
    {
      id: "travel",
      source: "poi_geojson",
      type: "symbol",
      layout: {
        "text-anchor": "top",
        "text-field": "{name}",
        "text-font": ["Noto Sans Regular"],
        "text-offset": [0, 0.8],
        "text-padding": 2,
        "text-size": 14,
        "icon-image": "{subclass}",
        "text-max-width": 30,
      },
      paint: {
        "text-color": [
          "case",
          ["boolean", ["feature-state", "hover"], false],
          "rgba(3, 117, 214, 1)",
          "#127F1F",
        ],
        "text-halo-color": "#ffffff",
        "text-halo-width": 1,
      },
      filter: ["all", ["==", "status", "Active"], ["==", "class", "旅遊"]],
    },
    {
      id: "clothes",
      source: "poi_geojson",
      type: "symbol",
      layout: {
        "text-anchor": "top",
        "text-field": "{name}",
        "text-font": ["Noto Sans Regular"],
        "text-offset": [0, 0.8],
        "text-padding": 2,
        "text-size": 14,
        "icon-image": "{subclass}",
        "text-max-width": 30,
      },
      paint: {
        "text-color": [
          "case",
          ["boolean", ["feature-state", "hover"], false],
          "rgba(3, 117, 214, 1)",
          "#1F9745",
        ],
        "text-halo-color": "#ffffff",
        "text-halo-width": 1,
      },
      filter: ["all", ["==", "status", "Active"], ["==", "class", "服飾"]],
    },
    {
      id: "sports",
      source: "poi_geojson",
      type: "symbol",
      layout: {
        "text-anchor": "top",
        "text-field": "{name}",
        "text-font": ["Noto Sans Regular"],
        "text-offset": [0, 0.8],
        "text-padding": 2,
        "text-size": 14,
        "icon-image": "{subclass}",
        "text-max-width": 30,
      },
      paint: {
        "text-color": [
          "case",
          ["boolean", ["feature-state", "hover"], false],
          "rgba(3, 117, 214, 1)",
          "#127F1F",
        ],
        "text-halo-color": "#ffffff",
        "text-halo-width": 1,
      },
      filter: ["all", ["==", "status", "Active"], ["==", "class", "運動"]],
    },
    {
      id: "medical",
      source: "poi_geojson",
      type: "symbol",
      layout: {
        "text-anchor": "top",
        "text-field": "{name}",
        "text-font": ["Noto Sans Regular"],
        "text-offset": [0, 0.8],
        "text-padding": 2,
        "text-size": 14,
        "icon-image": "{subclass}",
        "text-max-width": 30,
      },
      paint: {
        "text-color": [
          "case",
          ["boolean", ["feature-state", "hover"], false],
          "rgba(3, 117, 214, 1)",
          "#D74322",
        ],
        "text-halo-color": "#ffffff",
        "text-halo-width": 1,
      },
      filter: ["all", ["==", "status", "Active"], ["==", "class", "醫療"]],
    },
    {
      id: "restaurant",
      source: "poi_geojson",
      type: "symbol",
      layout: {
        "text-anchor": "top",
        "text-field": "{name}",
        "text-font": ["Noto Sans Regular"],
        "text-offset": [0, 0.8],
        "text-padding": 2,
        "text-size": 14,
        "icon-image": "{subclass}",
        "text-max-width": 30,
      },
      paint: {
        "text-color": [
          "case",
          ["boolean", ["feature-state", "hover"], false],
          "rgba(3, 117, 214, 1)",
          "#D77E1F",
        ],
        "text-halo-color": "#ffffff",
        "text-halo-width": 1,
      },
      filter: ["all", ["==", "status", "Active"], ["==", "class", "餐廳"]],
    },
    {
      id: "company",
      source: "company_geojson",
      type: "symbol",
      layout: {
        "text-anchor": "top",
        "text-field": "{name}\n{name:en}",
        "text-font": ["Noto Sans Regular"],
        "text-offset": [0, 0.8],
        "text-padding": 2,
        "text-size": 14,
        "icon-image": "trend_micro",
      },
      paint: {
        "text-color": [
          "case",
          ["boolean", ["feature-state", "hover"], false],
          "rgba(3, 117, 214, 1)",
          "#1544AF",
        ],
        "text-halo-blur": 0.5,
        "text-halo-color": "#ffffff",
        "text-halo-width": 1,
      },
    },
    {
      id: "selected_layer",
      source: "selected_geojson",
      type: "symbol",
      layout: {
        "text-anchor": "left",
        "text-field": "{name}",
        "text-font": ["Noto Sans Bold"],
        "text-offset": [1, 0],
        "text-padding": 2,
        "text-size": 16,
        "icon-image": "selected_icon",
        "text-max-width": 30,
        visibility: "visible",
      },
      paint: {
        "text-color": [
          "case",
          ["boolean", ["feature-state", "hover"], false],
          "rgba(3, 117, 214, 1)",
          "#E55547",
        ],
        "text-halo-color": "#ffffff",
        "text-halo-width": 1,
      },
    },
  ],
};
