name: Build App
on:
  pull_request:
    branches:
      - main
    types: [closed]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Build-App:
    if: (github.event.pull_request.merged == true || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install python package
        run: |
          python -m pip install --upgrade pip
          pip install csv2geojson
      - name: Create poi geojson from google sheets
        working-directory: ./.github/workflows
        run: sh fetch_data.sh
      - name: Build static file
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MAP_DEPLOY_TOKEN }}
          publish_dir: ./build/
